MasterCruelty/eMerger

- LICENSE
- README.md
- updater.sh
> Added a couple of commands

- README.md
- updater.sh
Added more systems. Fixed README.md
> Add feature

- updater.sh
Green colour and a function for printing progress
> :lipstick: new colour and more

- updater.sh
> Add Gentoo

- updater.sh
> Add trash cleaner

- updater.sh
Added `pkg`, moved it with `emerge` on top.
Made a proper access feature.
Tested on [Termux](https://termux.com/) too.
> Few features

- setup.sh
- uninstall.sh
- updater.sh
> Add uninstall

- AUTHORS
- README.md
- setup.sh
- src/updater.sh
- uninstall.sh
Added autoremove and fixed typos
> Add dnf autoremove

- src/systems/archlinux.sh
- src/systems/debian.sh
- src/systems/fedora.sh
- src/systems/gentoo.sh
- src/systems/termux.sh
- src/updater.sh
Created ```systems``` folder with a sh file for every supported system. Now ```updater.sh``` source file is more clean.
This should close #20
> :file_folder: Create systems folder closes #20

- src/package/archlinux.sh
- src/package/debian.sh
- src/package/flatpak.sh
- src/package/gentoo.sh
- src/package/rpm.sh
- src/package/snap.sh
- src/package/termux.sh
- src/updater.sh
- src/utils/privileges.sh
- src/utils/trash.sh
> Add and Fix

- .gitignore
- setup.sh
- src/package/archlinux.sh
- src/package/debian.sh
- src/package/flatpak.sh
- src/package/gentoo.sh
- src/package/rpm.sh
- src/package/snap.sh
- src/package/termux.sh
- src/updater.sh
- src/utils/cachegen.sh
- src/utils/checkpwr.sh
- src/utils/global.sh
- src/utils/trash.sh
- uninstall.sh
> Add cache system

- src/package/opensuse.sh
- src/utils/cachegen.sh
- src/utils/global.sh
> Add zypper

- src/test/integrity_check.sh
A first test file to check existence of every source files.
> :construction: Create test

- src/test/integrity_check.sh
- src/utils/package
- src/utils/utils
Improved ```integrity_check.sh```
> Improved test file

- setup.sh
- src/test/integrity_check.sh
- src/utils/cache_gen.sh
- uninstall.sh
> Refactor code

- fetch.sh
- setup.sh
- uninstall.sh
Created ```fetch.sh``` to get in touch with the repository and update the application whenever you want.
The file do a git pull and then launch ```uninstall.sh``` and ```setup.sh```
> :rocket: Added a fetch file to update from git

- src/package/debian.sh
Added clean command to `debian.sh`
> Modify debian

- setup.sh
- src/package/.packages
- src/package/arch.sh
- src/package/debian.sh
- src/package/flatpak.sh
- src/package/gentoo.sh
- src/package/opensuse.sh
- src/package/rpm.sh
- src/package/snap.sh
- src/package/termux.sh
- src/test/integrity_check.sh
- src/utils/cache_gen.sh
- src/utils/global.sh
- src/utils/privileges.sh
- src/utils/trash.sh
- uninstall.sh
> Add emoji :bug: 

- README.md
- license/WTTR_LICENSE
- src/emerger.sh
Added weather to script.
Changed the way a distribution is showed.
> Add weather

- README.md
- src/emerger.sh
> Fix retriever

- CONTRIBUTING.md
- README.md
- src/emerger.sh
- src/utils/help
- src/utils/privileges.sh
- src/utils/trash.sh
Added some arguments and a manual (#56)
> Add arguments

- src/emerger.sh
- src/test/argument_check.sh
- src/test/integrity_check.sh
- src/utils/global.sh
- src/utils/help
- I changed the colour of crossmarks in <code>integrity_check.sh</code>
- I updated <b>printProgress</b> function to recognize another word .
- I added a furhter condition in <code>emerger.sh</code> to verify and tell to the user if <code>.errors</code> is containing something. Solving #60
> Refactor and improve error tracking

- .gitignore
- README.md
- setup.sh
- src/emerger.sh
- src/package/arch.sh
- src/package/debian.sh
- src/package/flatpak.sh
- src/package/gentoo.sh
- src/package/nix.sh
- src/package/opensuse.sh
- src/package/rpm.sh
- src/package/snap.sh
- src/package/termux.sh
- src/test/argument_check.sh
- src/test/integrity_check.sh
- src/utils/cron.sh
- src/utils/global.sh
- src/utils/privileges.sh
- src/utils/trash.sh
- uninstall.sh
- update.sh
Solved #78 
Refactored `printProgress`, now it's called `put` and it works using a switch case.
> Bug fix and refactor

- src/emerger.sh
Added the path of <code>.log</code> when you type <code>up -err</code>
> :rocket:  Improve error tracking

- src/package/debian.sh
> Add autoremove

- src/emerger.sh
I refactored this pipeline and made it shorter and easier to read.
> :recycle: Refactor pipe

- src/emerger.sh
- src/utils/cache.sh
- src/utils/cache_gen.sh
- src/utils/help
- src/utils/trash.sh
> Add cache clearer

- src/package/debian.sh
> Fix Debian bug
